services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file: judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=1000'

  redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$${REDIS_PASSWORD}"',
      ]
    env_file: judge0.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - RAILS_ENV=production
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    privileged: true
    restart: always
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  cache:
    driver: local
