services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file: judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=1000'
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$${REDIS_PASSWORD}"',
      ]
    env_file: judge0.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    restart: always
    ports:
      - "5001:5001" # Changed to avoid conflict with express-app
    volumes:
      - ./apps/server:/app/apps/server
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://:$${REDIS_PASSWORD}@redis:6379
    networks:
      - app-network

  judge0:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - RAILS_ENV=production
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    networks:
      - app-network

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    privileged: true
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  cache:
    driver: local

networks:
  app-network:
    driver: bridge
